/**
 * Machine-readable error codes returned to clients via `ApiError.errorCode`.
 * Frontends switch on these — keep them stable.
 */
export const ErrorCode = {
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  CONFLICT: 'CONFLICT',

  // Auth / OTP
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  OTP_NOT_REQUESTED: 'OTP_NOT_REQUESTED',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',

  // Account / access
  EMAIL_BLACKLISTED: 'EMAIL_BLACKLISTED',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',

  // Sessions
  SESSION_LIMIT_EXCEEDED: 'SESSION_LIMIT_EXCEEDED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  TRUSTED_DEVICE_INVALID: 'TRUSTED_DEVICE_INVALID',

  // Domain (used by other modules)
  ALREADY_ENROLLED: 'ALREADY_ENROLLED',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  COUPON_INVALID: 'COUPON_INVALID',
  ACCESS_NOT_ENROLLED: 'ACCESS_NOT_ENROLLED',
  OWNERSHIP_REQUIRED: 'OWNERSHIP_REQUIRED',
  COURSE_NOT_PUBLISHABLE: 'COURSE_NOT_PUBLISHABLE',
  VIDEO_NOT_READY: 'VIDEO_NOT_READY',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  INTEGRATION_NOT_CONFIGURED: 'INTEGRATION_NOT_CONFIGURED',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
